#!/bin/bash

### BEGIN INIT INFO
# Provides:          ratelimit-policyd
# Required-Start:    $all
# Required-Stop:     $local_fs $remote_fs $syslog $named $network
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start SMTP Policy Daemon
# Description:       SMTP Rate Limit Policy Daemon
### END INIT INFO

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

INSTALL_DIR=/opt/send_rate_policyd
DAEMON=$INSTALL_DIR/daemon.pl
STOPSCRIPT=/usr/bin/perl
RUNAS=postfix
NAME=ratelimit-policyd
PIDFILE=/var/run/$NAME.pid
DESC="SMTP Rate Limit Policy Daemon"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
        start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON --chuid $RUNAS
        echo "."
        ;;
  status)
        $DAEMON printshm
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
        start-stop-daemon --stop --oknodo --pidfile $PIDFILE --exec $STOPSCRIPT && rm -f $PIDFILE
        echo "."
        ;;
  restart|force-reload)
        #
        #       If the "reload" option is implemented, move the "force-reload"
        #       option to the "reload" entry above. If not, "force-reload" is
        #       just the same as "restart".
        #
        $0 stop && sleep 2 && $0 start
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
